import type { Metadata } from "next";
import Header from "../../components/Header";
export const metadata: Metadata={title:"Frequently Asked Questions | Soilva",description:"Answers about Soilva products, Kandap grinding, storage and distributor enquiries."};
const faqs=[{ question: 'What is Soilva?', answer: 'Soilva is an Indian spice brand built around the philosophy From Soil to Soul, with a focus on thoughtful sourcing, defined processing and honest communication.' },
{ question: 'What does Kandap grinding mean?', answer: 'Kandap grinding refers to a traditional-inspired grinding approach. Soilva avoids unsupported health or performance claims.' },
{ question: 'Which products does Soilva offer?', answer: 'The planned range includes core everyday spices and blended masalas such as red chilli, turmeric, coriander, cumin, black pepper, garam masala and Kitchen King masala.' },
{ question: 'Where can I buy Soilva products?', answer: 'Availability depends on the launch market and approved retail partners. Contact Soilva to ask about your area.' },
{ question: 'Can I become a Soilva distributor?', answer: 'Yes. Eligible distributors, wholesalers and retail suppliers can apply through the Distributor Program page.' },
{ question: 'How should spices be stored?', answer: 'Keep sealed in a cool, dry place away from direct sunlight and moisture, and follow the final product label.' },];
export default function FAQPage(){const data={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};return <div className="site-shell"><Header/><main className="faq-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data)}}/><section className="faq-hero"><span className="about-kicker">Questions & answers</span><h1>Clear answers build stronger trust.</h1><p>Learn more about Soilva products, process, availability and partnerships.</p></section><section className="faq-list">{faqs.map((f,i)=><details key={f.question}><summary><span>{String(i+1).padStart(2,"0")}</span><strong>{f.question}</strong><i>+</i></summary><p>{f.answer}</p></details>)}</section></main></div>}